openapi: "3.0.0"
info:
  title: Simple API overview
  version: 1.0.0
paths:
  /users/me/profile:
    get:
      tags:
        - profile
      operationId: getUserProfile
      summary: Returns personal user data
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value:
                    {
                      "firstName": "Jane",
                      "lastName": "Doe",
                      "streetAddress": "1201 Peachtree Street NE",
                      "city": "Atlanta",
                      "state": "GA",
                      "zip": 30361,
                      "phone": 4048792261
                    }
              schema:
                $ref: '#/components/schemas/UserProfile'
components:
  schemas:
    UserProfile:
      type: object
      required:
        - address
        - zip
        - phone
      properties:
        firstName:
          type: string
        lastName:
          type: string
        streetAddress:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: number
        phone:
          type: number